### ISSUE TITLE
Display code panel

### ISSUE THREAD

**Issue by dmpe** [dmpe/shiny#8]
**Beginning:**
068
![obrazek](https://cloud.githubusercontent.com/assets/1799661/24423891/f06b0224-13fe-11e7-85b1-8d07b74b8ff2.png)

**As of now:** (only after `display : hidden` is deleted)
![image](https://cloud.githubusercontent.com/assets/1799661/24710680/2dd9b2de-1a1e-11e7-81b3-ce3fefcbc1e1.png)

https://github.com/rstudio/shiny/search?utf8=%E2%9C%93&q=showcase-code-position-toggle&type=

- [ ] Issue, in part at least, is that even though `style="width: 960px;"` is respected within the first `<td>`, we have `showcase-sxs-code-collapsed` that is hidden when loaded due to dynamic JS code. 
- [ ] The code is properly shown only when browser is adjusted so that code is below. This is by default.

- [ ] Picture gets created with wrong width.
>{"errors":[],"values":{"plot":{"src":"session/f6e6b29e93c457bbfd558f5d3111ae9b/file/plot?w=&r=c3685610456ef0c8","width":999,"height":400,"coordmap":[{"domain":{"left":-3.78,"right":3.78,"bottom":-4.4,"top":114.4},"range":{"left":59.0399999999999,"right":968.76,"bottom":325.56,"top":58.04},"log":{"x":null,"y":null},"mapping":{}}]}},"inputMessages":[]}

960 is appWidth
1150 is totalWidth

**Comment by dmpe** [comment]
http://docs.rstudio.com/shiny-server/#disabling-websockets-on-the-server
https://github.com/rstudio/   shiny-server/issues/237

**Comment by dmpe** [comment]
https://github.com/rstudio/shiny/issues/1659

**Comment by dmpe** [comment]
to test also https://bs40.k/084-single-file/ in showcase mode

https://bs40.k/088-action-pattern1/

**Comment by dmpe** [comment]
how it is now
![obrazek](https://cloud.githubusercontent.com/assets/1799661/26794023/6aa81ea8-4a20-11e7-8686-1050a838bd57.png)

vs how it should be 

![obrazek](https://cloud.githubusercontent.com/assets/1799661/26794112/bf161a76-4a20-11e7-9731-7f5aad224938.png)

vs how it was (see picture in first comment) = without border on tabs
